# Automatically Generated Makefile by EDE.
# For use with: make
#
# DO NOT MODIFY THIS FILE OR YOUR CHANGES MAY BE LOST.
# EDE is the Emacs Development Environment.
# http://cedet.sourceforge.net/ede.shtml
#

top="$(CURDIR)"/
ede_FILES=Project.ede Makefile

Adaptive CPP_SOURCES=factory_data_seq.cpp bench.cpp default_cost_swap.cpp default_cost_var.cpp default_display_sol.cpp default_exec_swap.cpp default_next_i.cpp default_next_j.cpp default_reset.cpp factory_data_par.cpp magic_square.cpp
Adaptive CPP_OBJ= factory_data_seq.o bench.o default_cost_swap.o default_cost_var.o default_display_sol.o default_exec_swap.o default_next_i.o default_next_j.o default_reset.o factory_data_par.o magic_square.o
CXX= g++
CXX_COMPILE=$(CXX) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
CXX_DEPENDENCIES=-Wp,-MD,.deps/$(*F).P
CXX_LINK=$(CXX) $(CFLAGS) $(LDFLAGS) -L.
VERSION=1.0
DISTDIR=$(top)Adaptive CPP-$(VERSION)
top_builddir = 

DEP_FILES=.deps/factory_data_seq.P .deps/bench.P .deps/default_cost_swap.P .deps/default_cost_var.P .deps/default_display_sol.P .deps/default_exec_swap.P .deps/default_next_i.P .deps/default_next_j.P .deps/default_reset.P .deps/factory_data_par.P .deps/magic_square.P .deps/ad_data.P .deps/ad_data_parallel.P .deps/bench.P .deps/default_cost_swap.P .deps/default_cost_var.P .deps/default_display_sol.P .deps/default_exec_swap.P .deps/default_next_i.P .deps/default_next_j.P .deps/default_reset.P .deps/factory_data.P .deps/factory_data_par.P .deps/factory_data_seq.P .deps/magic_square.P .deps/strategy_cost_swap.P .deps/strategy_cost_var.P .deps/strategy_display_sol.P .deps/strategy_exec_swap.P .deps/strategy_next_i.P .deps/strategy_next_j.P .deps/strategy_reset.P

all: Adaptive CPP

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)
-include $(DEP_FILES)

%.o: %.cpp
	@echo '$(CXX_COMPILE) -c $<'; \
	$(CXX_COMPILE) $(CXX_DEPENDENCIES) -o $@ -c $<

Adaptive CPP: $(Adaptive CPP_OBJ)
	$(CXX_LINK) -o $@ $^ $(LDDEPS)

tags: 


clean:
	rm -f *.mod *.o *.obj .deps/*.P .lo

.PHONY: dist

dist:
	rm -rf $(DISTDIR)
	mkdir $(DISTDIR)
	cp $(Adaptive CPP_SOURCES) $(ede_FILES) $(DISTDIR)
	tar -cvzf $(DISTDIR).tar.gz $(DISTDIR)
	rm -rf $(DISTDIR)

Makefile: Project.ede
	@echo Makefile is out of date!  It needs to be regenerated by EDE.
	@echo If you have not modified Project.ede, you can use 'touch' to update the Makefile time stamp.
	@false



# End of Makefile
